services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    env_file:
      - ./Backend/.env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    ports:
      - "3003:3003"


  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./Frontend/.env
      

  nginx:
    depends_on:
      - backend
      - frontend
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - ./Backend/.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./Backend/database_initial:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    

volumes:
  postgres-data:
