
CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  picture VARCHAR(100),
  role VARCHAR(10) NOT NULL DEFAULT 'user',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
); 

CREATE TABLE IF NOT EXISTS invited_emails (
  id SERIAL PRIMARY KEY,
  email VARCHAR(100) NOT NULL UNIQUE
); 

CREATE TABLE IF NOT EXISTS seasons (
  id SERIAL PRIMARY KEY,
  name VARCHAR(25) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS settings (
  id SERIAL PRIMARY KEY,
  key VARCHAR(50) NOT NULL UNIQUE,
  value VARCHAR(50) NOT NULL
);


CREATE TABLE IF NOT EXISTS games (
  id SERIAL PRIMARY KEY,
  home_team VARCHAR(50) NOT NULL,
  away_team VARCHAR(50) NOT NULL,
  home_score INT,
  away_score INT,
  game_date TIMESTAMPTZ NOT NULL,
  seasonid INT REFERENCES seasons(id) ON DELETE CASCADE NOT NULL,
);



CREATE TABLE IF NOT EXISTS players (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  nickname VARCHAR(50),
  number INT NOT NULL
);

CREATE TABLE IF NOT EXISTS points (
  player_id INT NOT NULL,
  game_id INT NOT NULL,
  goals INT NOT NULL,
  assists INT NOT NULL,
  pm INT NOT NULL,
  FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE,
  FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
  PRIMARY KEY (player_id, game_id)
);