DO
$$
BEGIN
  IF NOT EXISTS (
    SELECT
    FROM   pg_catalog.pg_roles
    WHERE  rolname = '${MYUSER}'
  ) THEN
    EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${MYUSER}', '${MYPASSWORD}');
  END IF;
END
$$;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${MYUSER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${MYUSER};
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ${MYUSER};