name: Deploy to VM 

on: 
  push: 
    branches: 
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name : Checkout repo
        uses: actions/checkout@v4


      - name: Deploy to VM
        if: success()
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd Rouhijat/
            git pull

            backend_container=$(docker compose ps -q backend)

            echo "Copying latest schema.prisma to container..."
            docker cp ./Backend/prisma/schema.prisma $backend_container:/app/prisma/schema.prisma

            echo "Creating Prisma migration..."
            docker exec $backend_container npx prisma migrate dev --create-only --name init

            echo "Copying migration files to host..."
            docker cp $backend_container:/app/prisma/migrations ./Backend/prisma

            docker compose down
            docker compose up --build -d

            docker image prune -f

            echo "Deployed successfully"

