name: Deploy to VM 

on: 
  push: 
    branches: 
      - main

jobs:
  lint-test:
    uses: ./.github/workflows/lint-test.yml

  deploy:
    needs: lint-test
    runs-on: ubuntu-latest

    steps:
      - name : Checkout repo
        uses: actions/checkout@v4


      - name: Deploy to VM
        if: success()
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd Rouhijat/
            git pull
            docker compose down
            docker compose up --build -d

            docker image prune -f

            echo "Deployed successfully"


# TODO: Add more tests to make sure the deployment is successful
