name: Build Docker image

on:
  push:
    branches:
      - main



jobs:
  lint: 
    name: Lint
    uses: ./.github/workflows/lint-test.yml


    # Add testing that builds all and tests that all works